version: "3.9"

services:
  web:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - dev.env