# Generated by Django 3.2.10 on 2022-11-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=8)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_pictures/employees')),
                ('phone_number', models.IntegerField(max_length=30, null=True)),
                ('alternative_phone_number', models.IntegerField(max_length=30)),
                ('skype', models.CharField(max_length=30, null=True)),
                ('mailing_address', models.CharField(max_length=50, null=True)),
                ('alternative_address', models.CharField(max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
