# Generated by Django 3.2.10 on 2022-11-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20221127_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('show_hide', models.BooleanField(default=False)),
                ('employeeprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeesprofile')),
                ('sociallinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.sociallinks')),
            ],
        ),
        migrations.AddField(
            model_name='employeesprofile',
            name='sociallinks',
            field=models.ManyToManyField(through='employees.EmployeeSocialLinks', to='employees.SocialLinks'),
        ),
    ]
